# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "Qwen2.5-Coder-32B-Instruct"  # or gpt-3.5-turbo
  base_url: "http://10.0.180.12:8800/v1"  # or forward url / other llm url
  api_key: "123"